#!/bin/bash

echo "🚀 ShaadiSetGo - GitHub Push Script"
echo "===================================="
echo ""
echo "Step 1: Personal Access Token Banao"
echo "------------------------------------"
echo "1. GitHub.com pe login karo"
echo "2. Click karo: Profile Photo → Settings"
echo "3. Left sidebar me: Developer settings"
echo "4. Personal access tokens → Tokens (classic)"
echo "5. 'Generate new token (classic)' click karo"
echo "6. Note: 'ShaadiSetGo Push' likho"
echo "7. Expiration: 'No expiration' select karo"
echo "8. Scopes me ye check karo:"
echo "   ☑ repo (full control)"
echo "9. 'Generate token' click karo"
echo "10. Token COPY karo (sirf ek baar dikhega!)"
echo ""
echo "Step 2: Terminal me ye command run karo"
echo "----------------------------------------"
echo "cd /home/z/my-project"
echo ""
echo "git push https://YOUR_TOKEN@github.com/Rohit001173/Shaadisetgo.git main"
echo ""
echo "Example (token ko replace karo):"
echo "git push https://ghp_xxxxxxxxxxxx@github.com/Rohit001173/Shaadisetgo.git main"
echo ""
echo "===================================="
echo "✅ Push successful ho jayega!"
